### ISSUE TITLE
Issue: GET Forbidden - 0.96.0

### ISSUE THREAD

**Issue by NautiqueSpcae** [ogame-ninja/scripts#57]
Since update the bot stopped working. I reversed to 0.95.3, however that didn't solve the issue.

Get "https://s141-nl.ogame.gameforge.com/game/lobbylogin.php?id=101093&token=d8f3ca1a-f127-4c03-a0b0-c6eec97c2320": Forbidden

**Comment by ogame-ninja** [comment]
https://ogameninja.slack.com/archives/C010FGSK42J/p1610143922045100
